# Generated by Django 2.0.3 on 2018-05-22 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='area',
            field=models.CharField(default=int, max_length=255),
            preserve_default=False,
        ),
    ]
