# Generated by Django 2.0.4 on 2018-06-01 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_concept_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concept',
            name='user',
        ),
    ]
