# Generated by Django 2.0.4 on 2018-06-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_remove_concept_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='long_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
