# Generated by Django 2.0.6 on 2018-06-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_concept_long_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='example',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
    ]
