# Generated by Django 2.0.5 on 2018-06-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_concept_example'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='area',
            field=models.CharField(choices=[('APP', 'Apps'), ('DJG', 'Django'), ('DOC', 'Docker'), ('GEN', 'General'), ('GIT', 'Git'), ('HTML', 'HTML & CSS'), ('JS', 'JavaScript'), ('JQ', 'jQuery'), ('PY', 'Python')], default='APP', max_length=255, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='long_description',
            field=models.TextField(blank=True, default='', verbose_name='Long Description'),
        ),
    ]
