# Generated by Django 2.0.6 on 2018-06-13 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0008_auto_20180612_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
