# Generated by Django 2.0.5 on 2018-07-09 21:54

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0010_auto_20180622_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='content',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
    ]
